language: python
sudo: false
python:
  - 3.5
matrix:
  include:
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=py37
      python: 3.7
before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.5
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - codecov
